[package]
name = "jit_streamer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "*", features = [ "full" ] }
warp = { version = "*" }
futures = { version = "*" }
bytes = { version = "*" }
serde = { version = "*", features = [ "derive" ] }
serde_json = { version = "*" }
rusty_libimobiledevice = { version = "*", path = "../rusty_libimobiledevice", features = [ "static" ] }
plist_plus = { version = "*", path= "../plist_plus", features = [ "static" ] }
dirs = { version = "*" }
reqwest = { version = "*", features = [ "blocking" ] }
zip = { version = "*" }
