[package]
name = "jit_streamer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

default-run = "jit_streamer"

[dependencies]
tokio = { version = "*", features = [ "full" ] }
warp = { version = "*", features = [ "tls" ] }
futures = { version = "*" }
bytes = { version = "*" }
serde = { version = "*", features = [ "derive" ] }
serde_json = { version = "*" }
rusty_libimobiledevice = { version = "*", path = "../rusty_libimobiledevice", features = [ "static", "vendored" ] }
plist_plus = { version = "*", path= "../plist_plus", features = [ "static", "vendored" ] }
dirs = { version = "*" }
reqwest = { version = "*", features = [ "blocking" ] }
zip = { version = "*" }
log = { version = "*" }
env_logger = { version = "*" }
rand = { version = "*" }

[[bin]]
name = "pair"
path = "src/pair.rs"
